version: '3'

services:
  sajadv-api:
    build: people-manager-server/
    container_name: web-api
    volumes:
      - .:/home/jura/Projetos/git.softplan/people-manager/people-manager-server
    ports:
      - '8080:8080'
    depends_on:
      - sajadv-postgres
    networks:
      - sajadv-network
  sajadv-postgres:
    image: postgres
    container_name: sajadv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sajadv
    ports:
      - "5432:5432"
    networks:
      - sajadv-network
networks:
  sajadv-network:
    driver: bridge
