version: '3'

services:
  sajadv-angular:
    build: people-manager-cli/
    container_name: pm-cli
    ports:
      - 8081:80
    depends_on:
      - sajadv-api
  sajadv-api:
    build: people-manager-server/
    container_name: web-api
    volumes:
      - .:/home/jura/tmp
    ports:
      - '8080:8080'
    depends_on:
      - sajadv-postgres
  sajadv-postgres:
    image: postgres
    container_name: sajadv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sajadv
    ports:
      - "5432:5432"
      
networks:
  sajadv-network:
    driver: bridge
